- name: Install Nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: App pre-requisites
  ansible.builtin.import_task: app-preq.yml

- name: Download nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: schema setup
  ansible.builtin.import_task: app-preq.yml

